# Generated by Django 5.2.7 on 2026-04-01 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('technician', 'Technician'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', help_text='User role in the system', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(blank=True, help_text='Department name', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography', max_length=500, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('address', models.TextField(blank=True, help_text='Full address', null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact name and phone', max_length=200, null=True)),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications (one per line)', null=True)),
                ('hire_date', models.DateField(blank=True, help_text='Date of hire', null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='User must be approved by administrator before login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
