# Generated by Django 5.2.7 on 2026-04-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipment_location_alter_equipment_location_old'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='equipment.department'),
        ),
    ]
