# Generated by Django 6.0.2 on 2026-02-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('maintenance', '0002_maintenancetype_period_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Manufacturer name', max_length=100, unique=True)),
                ('country', models.CharField(blank=True, help_text='Country of origin', max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text='Manufacturer website', null=True)),
                ('contact_info', models.TextField(blank=True, help_text='Contact information', null=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='required_maintenance_types',
            field=models.ManyToManyField(blank=True, help_text='Types of maintenance required for this equipment (Calibration, OQ/PV, Technical Service)', related_name='applicable_equipment', to='maintenance.maintenancetype'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(help_text='Laboratory location', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('calibration', 'Calibration Required'), ('out_of_service', 'Out of Service')], default='operational', help_text='Current equipment status (auto-calculated based on maintenance/inspection dates)', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(help_text='Equipment manufacturer', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.manufacturer'),
        ),
    ]
