# Generated by Django 5.2.7 on 2026-02-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_manufacturer_equipment_required_maintenance_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='required_maintenance_types',
        ),
        migrations.AddField(
            model_name='equipment',
            name='check_interval_months',
            field=models.IntegerField(choices=[(1, 'Месечна'), (3, 'Тримесечна (3 месеца)'), (6, 'Шестмесечна (6 месеца)'), (12, 'Годишна')], default=12, help_text='Периодичност на проверки за пригодност'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='commissioning_date',
            field=models.DateField(blank=True, help_text='Дата на въвеждане в експлоатация', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='requires_calibration',
            field=models.BooleanField(default=False, help_text='Подлежи на калибровка (везни, pH метри и др.)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='requires_oq_pv',
            field=models.BooleanField(default=False, help_text='Подлежи на OQ/PV (Operational Qualification / Performance Validation)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='requires_technical_review',
            field=models.BooleanField(default=False, help_text='Подлежи на технически преглед'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(help_text='Категория оборудване', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(help_text='Локация в лабораторията', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(help_text='Производител', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.manufacturer'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(help_text='Модел', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, help_text='Допълнителни бележки', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(help_text='Сериен номер', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'В експлоатация'), ('pending_validation', 'Чака валидиране'), ('pending_calibration', 'Чака калибровка'), ('pending_technical_review', 'Чака технически преглед'), ('maintenance', 'На поддръжка'), ('out_of_service', 'Извън експлоатация')], default='active', help_text='Текущ статус (изчислява се автоматично на база дати)', max_length=30),
        ),
    ]
