# Generated by Django 5.2.7 on 2026-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipment_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'В експлоатация'), ('pending_validation', 'Чака валидиране'), ('pending_calibration', 'Чака калибровка'), ('pending_technical_review', 'Чака технически преглед'), ('pending_multiple', 'Чака множество проверки'), ('maintenance', 'На поддръжка'), ('out_of_service', 'Извън експлоатация')], default='active', help_text='Текущ статус (изчислява се автоматично на база дати)', max_length=30),
        ),
    ]
