# Generated by Django 5.2.7 on 2026-02-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код на звено')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('full_name', models.CharField(max_length=300, verbose_name='Пълно наименование')),
                ('manager', models.CharField(blank=True, max_length=200, verbose_name='Ръководител')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звена',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['asset_number'], 'verbose_name': 'Оборудване', 'verbose_name_plural': 'Оборудване'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория оборудване', 'verbose_name_plural': 'Категории оборудване'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Производител', 'verbose_name_plural': 'Производители'},
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Име')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Длъжност')),
                ('specialization', models.CharField(choices=[('electrical', 'Електротехник'), ('mechanical', 'Механик'), ('it', 'IT специалист'), ('metrology', 'Метролог'), ('quality_control', 'Контрол на качеството'), ('laboratory', 'Лаборант'), ('hvac', 'Отопление/Климатици'), ('safety', 'Пожарна безопасност'), ('general', 'Общи проверки'), ('other', 'Друго')], default='general', max_length=50, verbose_name='Специализация')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, help_text='Попълва се само ако е от външна фирма', max_length=200, verbose_name='Външна фирма')),
                ('certification', models.TextField(blank=True, verbose_name='Сертификати/Квалификации')),
                ('certification_expiry', models.DateField(blank=True, null=True, verbose_name='Валидност на сертификат до')),
                ('notes', models.TextField(blank=True, verbose_name='Забележки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='equipment.department', verbose_name='Звено')),
            ],
            options={
                'verbose_name': 'Техник',
                'verbose_name_plural': 'Техници',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Формат: E-1-102 (Категория-Етаж-Помещение)', max_length=20, unique=True, verbose_name='Код на локация')),
                ('category', models.CharField(choices=[('A', 'Категория A'), ('B', 'Категория B'), ('C', 'Категория C'), ('D', 'Категория D'), ('E', 'Категория E')], max_length=1, verbose_name='Категория')),
                ('floor', models.IntegerField(verbose_name='Етаж')),
                ('room_number', models.CharField(max_length=10, verbose_name='Номер на помещение')),
                ('name', models.CharField(help_text='Напр: Лаборатория ККП', max_length=200, verbose_name='Име на лаборатория/помещение')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Сграда')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площ (кв.м)')),
                ('responsible_person', models.CharField(blank=True, max_length=200, verbose_name='Отговорно лице')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('notes', models.TextField(blank=True, verbose_name='Забележки')),
                ('has_controlled_temperature', models.BooleanField(default=False, verbose_name='Контролирана температура')),
                ('has_controlled_humidity', models.BooleanField(default=False, verbose_name='Контролирана влажност')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='equipment.department', verbose_name='Звено')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['category', 'floor', 'room_number'],
                'unique_together': {('category', 'floor', 'room_number')},
            },
        ),
    ]
