# Generated by Django 5.2.7 on 2026-02-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_department_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='location',
            new_name='location_old',
        ),
    ]
