# Generated by Django 5.2.7 on 2026-02-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_rename_location_to_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Локация на оборудването', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='equipment.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location_old',
            field=models.CharField(blank=True, help_text='Стара локация (само текст)', max_length=200, null=True, verbose_name='Локация (старо поле)'),
        ),
    ]
