# Generated by Django 5.2.7 on 2026-04-02 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipment_location_alter_equipment_location_old'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Свързване с потребителски акаунт (само за вътрешни техници)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
    ]
