# Generated by Django 5.1.15 on 2026-04-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_technician_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Име на документ')),
                ('document_type', models.CharField(choices=[('manual', 'Ръководство'), ('certificate', 'Сертификат'), ('protocol', 'Протокол'), ('validation', 'Валидация'), ('sop', 'SOP'), ('drawing', 'Чертеж'), ('photo', 'Снимка'), ('other', 'Друг')], default='other', max_length=20, verbose_name='Тип')),
                ('file', models.FileField(upload_to='equipment_documents/%Y/%m/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на качване')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Версия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('equipment', models.ManyToManyField(blank=True, related_name='documents', to='equipment.equipment', verbose_name='Оборудване')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Качен от')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Име на таг')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвят (hex)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='tags', to='equipment.equipment', verbose_name='Оборудване')),
            ],
            options={
                'verbose_name': 'Таг',
                'verbose_name_plural': 'Тагове',
                'ordering': ['name'],
            },
        ),
    ]
