# Generated by Django 5.2.7 on 2026-02-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('calibration', 'Calibration'), ('validation', 'Validation'), ('technical_service', 'Technical Service'), ('repair', 'Repair')], max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Maintenance Type',
                'verbose_name_plural': 'Maintenance Types',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_date', models.DateField()),
                ('next_due_date', models.DateField(help_text='Дата на следващото калибриране/валидация')),
                ('performed_by', models.CharField(help_text='Отдел или име (напр. Метрологичен/КИП)', max_length=200)),
                ('certificate_number', models.CharField(blank=True, help_text='Номер на сертификат/протокол', max_length=100, null=True)),
                ('results', models.TextField(help_text='Резултати от калибрирането/валидацията')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='maintenance.maintenancetype')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-performed_date'],
            },
        ),
    ]
