# Generated by Django 6.0.2 on 2026-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetype',
            name='period_months',
            field=models.PositiveIntegerField(default=12, help_text='Period in months (e.g., 12 for annual, 6 for semi-annual)'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Certificate/Protocol number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Next due date (auto-calculated from performed_date + period)', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.CharField(help_text='Department or person name (e.g., Metrology/QC)', max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_date',
            field=models.DateField(help_text='Date when maintenance was performed'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='results',
            field=models.TextField(help_text='Calibration/Validation results'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='description',
            field=models.TextField(help_text='Description of the maintenance type'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='name',
            field=models.CharField(help_text='Maintenance type name', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='type',
            field=models.CharField(choices=[('calibration', 'Calibration'), ('validation', 'OQ/PV Validation'), ('technical_service', 'Technical Service'), ('repair', 'Repair')], max_length=20),
        ),
    ]
