# Generated by Django 5.2.7 on 2026-02-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipment_purchase_date_and_more'),
        ('maintenance', '0002_maintenancetype_period_months_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-performed_date'], 'verbose_name': 'Запис за поддръжка', 'verbose_name_plural': 'Записи за поддръжка'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Тип поддръжка', 'verbose_name_plural': 'Типове поддръжка'},
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='results',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='currency',
            field=models.CharField(choices=[('BGN', 'BGN (Лева)'), ('EUR', 'EUR (Евро)')], default='BGN', help_text='Валута', max_length=3),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='parts_used',
            field=models.TextField(blank=True, help_text='Използвани части/материали', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='result',
            field=models.CharField(choices=[('passed', 'Годен'), ('failed', 'Негоден'), ('conditional', 'Условно годен')], default='passed', help_text='Резултат от проверката', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='work_performed',
            field=models.TextField(blank=True, default='', help_text='Извършена работа/резултати'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Номер на сертификат/протокол', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='equipment',
            field=models.ForeignKey(help_text='Оборудване', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.ForeignKey(help_text='Тип поддръжка', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='maintenance.maintenancetype'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Следваща дата (автоматично изчислена от дата + период)', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Допълнителни бележки', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.CharField(help_text='Изпълнено от (отдел или име: Метрология/QC)', max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_date',
            field=models.DateField(help_text='Дата на изпълнение'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='description',
            field=models.TextField(help_text='Описание на типа поддръжка'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='name',
            field=models.CharField(help_text='Наименование на типа поддръжка', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='period_months',
            field=models.PositiveIntegerField(default=12, help_text='Периодичност в месеци (например: 12 за годишна, 6 за шестмесечна)'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='type',
            field=models.CharField(choices=[('calibration', 'Калибровка'), ('validation', 'OQ/PV Валидиране'), ('technical_service', 'Технически преглед'), ('repair', 'Ремонт')], help_text='Тип на поддръжката', max_length=20),
        ),
    ]
