# Generated by Django 5.2.7 on 2026-02-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipment_location_alter_equipment_location_old'),
        ('maintenance', '0003_alter_maintenancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Техник извършил поддръжката', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='equipment.technician', verbose_name='Техник/Изпълнител'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.CharField(blank=True, help_text='Изпълнено от (старо поле за справка)', max_length=200),
        ),
    ]
