# Generated by Django 5.2.7 on 2026-02-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип на проверката (дневна, месечна и т.н.)', max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', '3 Months'), ('biannual', '6 Months'), ('annual', 'Annual')], max_length=20)),
                ('description', models.TextField()),
                ('checklist', models.TextField(help_text='Списък с проверки, които трябва да се направят')),
            ],
            options={
                'verbose_name': 'Inspection Type',
                'verbose_name_plural': 'Inspection Types',
                'ordering': ['frequency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('next_inspection_date', models.DateField(help_text='Дата на следващата проверка')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('needs_attention', 'Needs Attention')], max_length=20)),
                ('inspector_name', models.CharField(help_text='Име на извършилия проверката', max_length=100)),
                ('findings', models.TextField(help_text='Резултати и забележки от проверката')),
                ('corrective_actions', models.TextField(blank=True, help_text='Коригиращи действия (ако има)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipment.equipment')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspections.inspectiontype')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
