# Generated by Django 6.0.2 on 2026-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='corrective_actions',
            field=models.TextField(blank=True, help_text='Corrective actions (if any)', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='findings',
            field=models.TextField(help_text='Inspection results and remarks'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(help_text='Date when inspection was performed'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector_name',
            field=models.CharField(help_text='Name of the inspector', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='next_inspection_date',
            field=models.DateField(blank=True, help_text='Next inspection date (auto-calculated from inspection_date + frequency)', null=True),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='checklist',
            field=models.TextField(help_text='List of checks to be performed'),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='description',
            field=models.TextField(help_text='Description of the inspection'),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='name',
            field=models.CharField(help_text='Inspection type name (daily, monthly, etc.)', max_length=100),
        ),
    ]
