# Generated by Django 5.2.7 on 2026-02-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipment_purchase_date_and_more'),
        ('inspections', '0002_alter_inspection_corrective_actions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-inspection_date'], 'verbose_name': 'Проверка', 'verbose_name_plural': 'Проверки'},
        ),
        migrations.AlterModelOptions(
            name='inspectiontype',
            options={'ordering': ['frequency', 'name'], 'verbose_name': 'Тип проверка', 'verbose_name_plural': 'Типове проверки'},
        ),
        migrations.AlterField(
            model_name='inspection',
            name='corrective_actions',
            field=models.TextField(blank=True, help_text='Коригиращи действия (ако има такива)', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='equipment',
            field=models.ForeignKey(help_text='Оборудване', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='findings',
            field=models.TextField(help_text='Констатации и резултати от проверката'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(help_text='Дата на изпълнение на проверката'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.ForeignKey(help_text='Тип проверка', on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspections.inspectiontype'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector_name',
            field=models.CharField(help_text='Име на проверяващия', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='next_inspection_date',
            field=models.DateField(blank=True, help_text='Следваща дата на проверка (автоматично изчислена)', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('passed', 'Годен'), ('failed', 'Негоден'), ('needs_attention', 'Изисква внимание')], help_text='Статус на проверката', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='checklist',
            field=models.TextField(help_text='Списък с проверки, които трябва да се изпълнят'),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='description',
            field=models.TextField(help_text='Описание на проверката'),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Дневна'), ('weekly', 'Седмична'), ('monthly', 'Месечна'), ('quarterly', 'Тримесечна (3 месеца)'), ('biannual', 'Шестмесечна (6 месеца)'), ('annual', 'Годишна')], help_text='Честота на проверката', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='name',
            field=models.CharField(help_text='Наименование на типа проверка', max_length=100),
        ),
    ]
