# Generated by Django 5.2.7 on 2026-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectiontype',
            options={'ordering': ['category', 'frequency', 'name'], 'verbose_name': 'Тип проверка', 'verbose_name_plural': 'Типове проверки'},
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='category',
            field=models.CharField(choices=[('technical_review', 'Технически преглед'), ('suitability_check', 'Проверка за пригодност')], default='suitability_check', help_text='Категория проверка', max_length=30),
        ),
    ]
