# Generated by Django 5.2.7 on 2026-02-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipment_location_alter_equipment_location_old'),
        ('inspections', '0004_alter_inspectiontype_options_inspectiontype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Техник извършил проверката', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='equipment.technician', verbose_name='Техник/Изпълнител'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector_name',
            field=models.CharField(blank=True, help_text='Име на проверяващия (старо поле за справка)', max_length=100),
        ),
    ]
